server.port:9000

#actuator
management.server.port:9001
management.server.address:127.0.0.1
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=loggers
management.endpoint.health.show-details=always

#pdf api processing
pdf.upload.url=https://api.chatpdf.com/v1/sources/add-file
pdf.chats.url=https://api.chatpdf.com/v1/chats/message
pdf.api.key.name=x-api-key
pdf.api.key.value=sec_fTnTJaRI76sATG0ME6jhM9CY5vuQ4aed

#internal db settings
spring.datasource.url=jdbc:h2:file:/tmp/xtracto/invoicesDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

invoices.upload.location=/tmp/xtracto/invoices

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.threads.virtual.enabled=true
